
export interface Contact {
    ID?: string,
    PHOTO?: FormData | any,
    NAME_PREFIX?: string,
    FIRST_NAME?: string,
    MIDDLE_NAME?: string,
    LAST_NAME?: string,
    MOTHERS_MAIDEN_NAME?: string,
    NAME_SUFIX?: string,
    NICKNAME?: string,
    PHONE1_VALUE?: string,
    PHONE1_TYPE?: string,
    PHONE2_VALUE?: string,
    PHONE2_TYPE?: string,
    EMAIL1_VALUE?: string,
    image?: string,
    ORGANIZATION1_NAME?: string
    ORGANIZATION1_DEPARTMENT?: string,
    ADDRESS1_TYPE?: string,
    ADDRESS1_STREET?: string,
    ADDRESS1_CITY?: string,
    ADDRESS1_REGION?: string,
    ADDRESS1_POSTAL_CODE?: string,
    ADDRESS1_COUNTRY?: string,
    ADDRESS_LABEL?: string,
    BIRTHDAY?: string,
    DATES_VALUES?: string,
    DATES_TYPES?: string,
    SOCIAL_VALUES?: string,
    SOCIAL_TYPES?: string,
    CONNECTIONS_VALUES?: string,
    CONNECTIONS_TYPES?: string,
    LANGUAGE?: string,
    ORIGIN_PLACES_VALUES?: string,
    ORIGIN_PLACES_TYPES?: string,
   
};